language: node_js
node_js:
- '0.8'
- '0.10'
- '0.11'
before_install:
- npm update -g npm@~1.4.6
deploy:
  provider: heroku
  api_key:
    secure: BKhNi0knWfJ803YIVxNg3WLpUvV7B7LCFqU0vIcuSMmx34h7wllGrp8FtvlVPL37hrbsWNTYJdn0tTX39yMwtO+EEqxUwKwIQwGvTWTifp/Wywa+jy7HBnpjgsam9jiKXjT23zrWb3gaMEOxXniOIWZzQpG+DyDJkq0W+vGklww=
  app:
    master: md-parse-html
  on:
    repo: tgfjt/md-parse-html
